config/routes.rb
Rails.application.routes.draw do
  
  # get 'homes/top'
  devise_for :users, controllers: {
  	sessions: 'users/sessions',
  	registrations: 'users/registrations'
  }
	root 'homes#top'
	get 'home/about' => 'homes#about'
	
	resources :users, only:[:show, :edit, :index]
 	resources :books, only: [:create, :index, :show, :edit, :update, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,dependent: :destroy

         validates :name,
         uniqueness: {case_sensitive: :false},
         length: {minimum:2, maximum:20}

         attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
		user_path(resource.id)
  	end

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
  def new
  	
  end
  
  def create
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
  	@book.save
  	redirect_to book_path(@book.id)
  end

  def index
    @books= Book.all
  end

  def show
  	@book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    book.update(book_params)
    redirect_to books_path
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
  	@user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	@user.update(user_params)
  	redirect_to user_path(@user.id)
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<!-- form_for部分 -->
<%= form_for(@book) do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Update Book' %>
<% end %>

<%= link_to "show",book_path(@book) %>|<%= link_to "back",books_path %>

app/views/books/index.html.erb
<div class="container-fluid">
	<div class="row sampleRow">
		<div class="col-xs-4">

			
		</div>
<div class="col-xs-8">
			<div class="bookdetail">
				<p>Books</p>
				<table class="table table-hover">
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
					</tr>
					<% @books.each do |book| %>
					<tr>
						<td><%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpg',  fallback:"no_image.jpg", size:'40x40' %></td>
						<td><%= book.title %></td>
						<td><%= book.body %></td>
					</tr>
					<% end %>
				</table>
			</div>

app/views/books/show.html.erb
<div class="container-fluid">
	<div class="row sampleRow">
		<div class="col-xs-4">

			<div class="user_info">
				<p>User info</p>

				<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg' %>
					<table class="table">
						<tr>
							<th>name</th>
							<th><%= @user.name %></th>
						</tr>
						<tr>
							<th>introduction</th>
							<th><%= @user.introduction %></th>
						</tr>
					</table>
				<%if @user.id == current_user.id %>
				<p><%= link_to("編集",edit_user_path(@user)) %></p>
				<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
				<% end %>

			</div>

				<div class="newpost">
					<p>new book</p>
					<%= form_for(@book_new) do |f| %>
					<h4>Title</h4>
					<%= f.text_field :title %>

					<h4>Opinion</h4>
					<%= f.text_area :body %>
					<br>
					<%= f.submit 'Create Book' %>
					<% end %>
				</div>

					<style>
					.sampleRow > div {
						border: 1px solid gray;
					}
					</style>
		</div>
		<div class="col-xs-8">
			<div class="bookdetail">
				<p>Bookdetail</p>
				<table>
					<tr>
						<th>アイコン</th>
						<th><%= @book.title %></th>
						<th><%= @book.body %></th>
						<th>
						<%= link_to "edit", edit_book_path(@book) %>
						</th>
						<th>
						<%= link_to "destroy", books_path(@book), method: :delete %>
						</th>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/homes/about.html.erb
<h2>Welcome to Bookers!</h2>

app/views/homes/top.html.erb
<h1>ログインアプリ</h1>

<% if user_signed_in? %> <!-- ユーザーがログインしているか調べる -->
  <!-- ユーザーがログインしていた時の処理 -->

  <h4> メールアドレス: <%= current_user.email %> </h4>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %> <!-- ログアウトをする -->
<% else %>
  <!-- ユーザーがログインしていなかった時の処理 -->
  <h2> 現在ログインしていません </h2>
  <%= link_to "ログイン", new_user_session_path, class: 'post' %> <!-- ログイン画面に移行する -->
  <%= link_to "新規登録", new_user_registration_path, class: 'post' %> <!-- 新規登録画面に移行する -->
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersLevel2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <div class="container-fluid">
    <div class="col-xs-12 header__float">
      <h1>Bookers</h1>
      
      <nav>
        <ul>
          <% if user_signed_in? %>
            <li><span class="glyphicon glyphicon-home" aria-hidden="true"></span>
              <%= link_to "Home",user_path(current_user.id) %></li>
            <li><span class="glyphicon glyphicon-user" aria-hidden="true"></span>user</li>
            <li><span class="glyphicon glyphicon-book" aria-hidden="true"></span>
            <%= link_to "Books",books_path %></li>

            <li><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
              <%= link_to "logout", destroy_user_session_path, method: :delete %></li>

            <% else %>

            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", home_about_path %></li>
            <li><%= link_to "sign up", new_user_registration_path %></li>
            <li><%= link_to "login", new_user_session_path %>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>


    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>User info</h1>

<%= form_for(@user) do |f| %>
        <h4>Name</h4>
    	<%= f.text_field :name %>
    	<h4>Image</h4>
    	<%= f.attachment_field :profile_image %>

    	<h4>Introduction</h4>
    	<%= f.text_area :introduction %>

    	<%= f.submit "Update User" %>



<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>

<div class="user_info">
	<p>User info</p>

	<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg' %>
	<table>
		<tr>
			<th>name</th>
			<th><%= @user.name %></th>
		</tr>
		<tr>
			<th>introduction</th>
			<th><%= @user.introduction %></th>
		</tr>
	</table>
	
</div>

<div class="newpost">
	<p>new book</p>
	
	<%= form_for(@book, url: 'books') do |f| %>
	<h4>Title</h4>
	<%= f.text_field :title %>

	<h4>Opinion</h4>
	<%= f.text_area :body %>

	<%= f.submit 'Create Book' %>
	<% end %>
</div> 

<div class="users">
	<p>Users</p>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>